### ISSUE TITLE
When Ship is the smallest player can escape game area by position it self in corner

### ISSUE THREAD

**Issue by KSYMEK** [soltys/TheShipGame#1]
When you change size of ship to the smallest and you will flight to corner and change size to bigger you can fly outside of game area

**Comment by soltys** [comment]
It's known issue, probably increasing game border to "Infinity" will help.

**Comment by soltys** [comment]
It took me only 1.5 year to complete this bug!

@KSYMEK :)

**Comment by KSYMEK** [comment]
Well done!
